### ISSUE TITLE
The mod is not loading in the game!! 

### ISSUE THREAD

**Issue by PSGitHubUser1** [ValkyrienSkies/Eureka#102]
I've tried like 50 times!!! but the beta5 of fabric is loading in game with library called 'Valkyrien Skies'. 

Versions:

 * Eureka: 1.1.0-beta5
 * Valkyrien Skies: 118-2.1.0-beta9

It is not loading! Here's the crash report...
[Crash Report [17-01-2023], 15:14 IST](https://github.com/ValkyrienSkies/Eureka/files/10433644/crash-2023-01-17_15.14.02-client.txt)

**Comment by PSGitHubUser1** [comment]
@copperwarrior sorry for ping but what I do now?

**Comment by Rubydesic** [comment]
Remove lithium
