### ISSUE TITLE
Collision box is too big

### ISSUE THREAD

**Issue by Slimekong** [ValkyrienSkies/Eureka#107]
When I try to assemble a Ship on the server, then it disapears for a while and then you cant move it. It is possible to use the Steering wheel, but nothing happens when you try to move. I am using PloudOs for the Server and in the log is the following message, when I assemble the ship:
`[15Jan2023 15:17:51.527] [Server thread/ERROR] [VS2 Get Entities Mixin/]: java.lang.Exception: Collision box is too big! AABB[-2.8665855650000006E7, 63.0, -126.80000001192093] -> [-141.19999998807907, 64.79999995231628, 1.2290051650000006E7] returning empty list! this might break things>`

Log:
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/10474457/latest.log)

Modlist:
Appleskin
Ars-Creo
Ars Nouveau
AutoRegLib
Buildersaddition
Buildinggadgets
Clumps
Controlling
Create
Create Addition
Create Confectionery
Creacte Deco
Create Stuff and Additions
Curios
Eureka
Flywheel
JEI
Journeymap
Kotlin
Mouse Tweaks
Patchoulie
Quark
Quark Oddities
Valkyrienskies
World Edit

**Comment by Slimekong** [comment]
I am using Forge 1.18.2 (40.1.92)

**Comment by copperwarrior** [comment]
Please provide a list of mods you are using, and the server logs when this happens.

**Comment by Slimekong** [comment]
> Please provide a list of mods you are using, and the server logs when this happens.

👍 Better?

**Comment by CainSidhe** [comment]
I have the same issue, it in addition caused an interesting visual bug where blocks are block during the night or white during the day, additionally breaking flowers that are effected by this break every other flower on that y level within a large radius that seems randomized.
mods i share with OP:
Appleskin
AutoRegLib
Clumps
Controlling
Curios
Eureka
JEI
Kotlin
Mouse Tweaks
Patchoulie
Quark
Valkyrienskies
![2023-01-24_20 21 07](https://user-images.githubusercontent.com/123529967/214479276-1185c658-bafc-489e-9716-158b35d1370f.png)
![2023-01-24_20 21 22](https://user-images.githubusercontent.com/123529967/214479289-97c6a5a5-c4e0-45e0-8cbe-c362f74ad2be.png)

**Comment by Slimekong** [comment]
Ok, I think it was an issue with the server provider PloudOS which is now shut down, so...
