### ISSUE TITLE
Turning off Engine makes ship lose all Buoyancy

### ISSUE THREAD

**Issue by JoeDingo** [ValkyrienSkies/Eureka#108]
Whenever I turn off the engine on my ship it loses all buoyancy. Please note that this is on my personal server and not singleplayer, although since the server is in my room with me it's not hard for me to get more data if you need it.

**Comment by copperwarrior** [comment]
Can you record a video of this in action, along with server logs and a list of mods you're using?

**Comment by Rubydesic** [comment]
stale and unable to reproduce
