### ISSUE TITLE
Incompatible with Lithium,

### ISSUE THREAD

**Issue by PWDSerialgamer07** [ValkyrienSkies/Eureka#113]
Eureka appears to be crashing my game when I launch it in Fabric 1.18.2. I have valkyrien skies installed and a bunch of other mods. Here is the log:
[Log](https://paste.atlauncher.com/view/a411745d-0eb5-48f9-9997-b0b1f02085bf)

**Comment by Rubydesic** [comment]
lithium incompatible

**Comment by walksanatora** [comment]
use rubidium in the mean time

**Comment by Rubydesic** [comment]
they do different things

**Comment by walksanatora** [comment]
ah sorry i am used to all the metalic sounding mods being rendering related

**Comment by Rubydesic** [comment]
The fix for this issue has already been pushed and will be part of the next Curseforge release.
