### ISSUE TITLE
When I trie to move my airship it barely moves  

### ISSUE THREAD

**Issue by sdfknjerflarfjhuvjased** [ValkyrienSkies/Eureka#118]
When I Tried to make a big airship when I assembled the airship it wouldn't move it would only barely change the angle and when I tried to remove the ship helm the ship wouldn't budge, can anyone give me any tips?  
![2023-01-20_19 46 06](https://user-images.githubusercontent.com/123221133/213840552-2429aad8-0e9e-4d8e-a02f-0e1858c33d59.png)

**Comment by ThePaste** [comment]
I think you have to add Ship engines and add coal to these
![Minecraft_ 1 18 2 - Multiplayer (3rd-party Server) 21_01_2023 14_31_44](https://user-images.githubusercontent.com/123248949/213869117-d2703273-6e2b-4182-81bd-f08b29136e1a.png)

**Comment by copperwarrior** [comment]
With all that obsidian your ship will be very heavy. Add more ship engines and then try to move it.

**Comment by sdfknjerflarfjhuvjased** [comment]
Hmmm I'll try that
