### ISSUE TITLE
When I assemble my airship it turns invisible

### ISSUE THREAD

**Issue by ThePaste** [ValkyrienSkies/Eureka#119]
![Minecraft_ 1 18 2 - Multiplayer (3rd-party Server) 21_01_2023 14_26_21](https://user-images.githubusercontent.com/123248949/213868905-b15a1721-62c1-44a8-91a8-705324f858da.png)

I made a normal airship, a base of 3x3 planks and beneath it a 3x3x2 of ballons, I assemble it and it turns invisible,  do I have to install any resource pack or it isn't compatible with aternos?

Help me the sooner the better pls

**Comment by Portaill** [comment]
It may a Optifine Probleme

**Comment by copperwarrior** [comment]
Please provide a list of mods.

**Comment by Rubydesic** [comment]
Optifine not supported in 1.18 use rubidium and oculus

**Comment by ThePaste** [comment]
> It may a Optifine Probleme

Ok thanks
