### ISSUE TITLE
cant see my ship when i assembled it

### ISSUE THREAD

**Issue by Lolinator3000000** [ValkyrienSkies/Eureka#124]
when i assemble my ship, it just goes invisible and i am frozen when i go the where it was

those are my mods:
AutoRegLib
Vazkii
AutoRegLib-1.7-53.jar

Better Third Person
Socolio
BetterThirdPerson-Forge-1.18.2-1.9.0.jar

♪ Boss Music Mod ♪
theexiiedfeiiow_
Boss Music Mod 1.18.jar

Creatures and Beasts
joosh_7889
CNB-1.18.2-1.5.0.jar

Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.18.2-v2a.jar

Decoration Delight
InfernoSakai
Decoration_Delight_Mod-1.18.2-1.0.2.jar

Delightful
brdbrn
Delightful-1.18.2-2.6.jar

Enigmatic Legacy
Aizistral
EnigmaticLegacy-2.25.0.jar

Farmer's Delight
vectorwing
FarmersDelight-1.18.2-1.2.0.jar

Festive Delight
to0pa_fr
Festive_Delight_1.0.jar

InsaneLib
Insane96MCP
InsaneLib-1.5.3-mc1.18.2.jar

Medieval Deco
PlayTics
Medieval Decoration v.1.0 1.18.jar

MmmMmmMmmMmm (Target Dummy)
MehVahdJukaar
MmmMmmMmmMmm-1.18.2-1.5.2.jar

Nether's Delight
lumpazl
NethersDelight-1.18.2-2.2.0.jar

Patchouli
Vazkii
Patchouli-1.18.2-71.1.jar

Progressive Bosses
Insane96MCP
ProgressiveBosses-3.6.5-mc1.18.2.jar

Quark
Vazkii
Quark-3.2-358.jar

YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.18.2-Forge-2.2.7.jar

YUNG's Better Desert Temples (Forge)
YUNGNICKYOUNG
YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar

YUNG's Better Ocean Monuments (Forge)
YUNGNICKYOUNG
YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar

YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar

YUNG's Bridges (Forge)
YUNGNICKYOUNG
YungsBridges-1.18.2-Forge-2.1.0.jar

YUNG's Extras (Forge)
YUNGNICKYOUNG
YungsExtras-1.18.2-Forge-2.1.0.jar

Epic Knights: Shields, Armor and Weapons
magistu_
[1.18.x]-Epic-Knights-Armor-and-Weapons-6.6v.jar

Alex's Delight
NCP_Bails
alexsdelight-1.18.2-1.3.3.jar

Alex's Mobs
sbom_xela
alexsmobs-1.18.6.jar

AppleSkin
squeek502
appleskin-forge-mc1.18.2-2.4.1.jar

Architectury API (Fabric/Forge)
shedaniel
architectury-4.10.88-forge.jar

Better Animals Plus
cybercat5555
betteranimalsplus-1.18.2-11.0.10-forge.jar

Better Combat [Fabric & Forge]
daedelus_dev
bettercombat-forge-1.5.5+1.18.2.jar

Better Invisibility
Purplicious_Cow_
betterinvisibility-1.18.1-1.0.4.jar

Better Villages - Forge
jtl_elisa
bettervillage-forge-1.18.2-2.0.0.jar

Blueprint
TeamAbnormals
blueprint-1.18.2-5.5.0.jar

Caelus API (Forge)
TheIllusiveC4
caelus-forge-1.18.1-3.0.0.2.jar

Citadel
sbom_xela
citadel-1.11.3-1.18.2.jar

Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-6.4.90-forge.jar

Corn Delight
sz0999312
corn_delight-1.0.6-1.18.2.jar

Create
simibubi
create-1.18.2-0.5.0.h.jar

Creeper Overhaul
joosh_7889
creeperoverhaul-1.3.1-forge.jar

Cultural Delights
NCP_Bails
culturaldelights-1.18.2-0.14.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.18.2-5.0.7.1.jar

Ecologics
SameDifferent
ecologics-forge-1.18.2-1.7.11.jar

End's Delight
foggyhillside
ends_delight-1.18.2-1.0.jar

Eureka! Airships! (Forge/Fabric)
rubydesic
eureka-1.1.0-beta5.jar

Fantasy's Furniture
ApexMdr
fantasyfurniture-1.18.2-3.14.0.jar

Flywheel
jozufozu
flywheel-forge-1.18.2-0.6.8.a.jar

GeckoLib
ThanosGecko
geckolib-forge-1.18-3.0.57.jar

Guard Villagers
almightytallestred
guardvillagers-1.18.2.1.4.3.jar

Immersive Portals (for Forge)
qouteall
immersive-portals-1.4.13-mc1.18.2-forge.jar

Immersive Weathering [FORGE]
OrdanaryMods
immersive_weathering-1.18.2-3.0.3-forge.jar

Iron Age Furniture
SkyBlade1978
ironagefurniture-1.18.2-0.2.0.10.jar

Just Enough Items (JEI)
mezz
jei-1.18.2-9.7.1.255.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-3.9.1-all.jar

Large Meals (An Add-on for Farmer's Delight)
LostWiz08
largemeals-1.18.2-2.0.jar

Library Ferret - Forge
jtl_elisa
libraryferret-forge-1.18.2-3.0.0.jar

Mahou Tsukai
stepcros
mahoutsukai-1.18.2-v1.34.38.jar

Majrusz Library
Majrusz17
majrusz-library-1.18.2-3.1.0.jar

Majrusz's Progressive Difficulty
Majrusz17
majruszs-difficulty-1.18.2-1.6.1.jar

Macaw's Bridges
sketch_macaw
mcw-bridges-2.0.6-mc1.18.2forge.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-2.2.2-mc1.18.2forge.jar

Mysterious Mountain Lib
sz0999312
mmlib-1.2.0-1.18.2.jar

More Villagers
SameDifferent
morevillagers-forge-1.18.2-3.3.2.jar

Mowzie's Mobs
bobmowzie
mowziesmobs-1.5.32.jar

Plasmo Voice
KPidS
plasmovoice-forge-1.18-1.2.19.jar

playerAnimator
KosmX
player-animation-lib-forge-0.4.2+1.18.jar

Savage & Ravage
TeamAbnormals
savage_and_ravage-1.18.2-4.0.0.jar

Moonlight Lib
MehVahdJukaar
selene-1.18.2-1.17.9.jar

Small Ships [Fabric & Forge]
talhanation
smallships-1.18.2-2.0.0-Alpha-0.4.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.18.2-3.18.40.777.jar

Sophisticated Core
P3pp3rF1y
sophisticatedcore-1.18.2-0.5.37.202.jar

Stalwart Dungeons
Furti_Two
stalwart-dungeons-1.18.2-1.2.3.jar

Valkyrien Skies (Forge/Fabric)
triode_
valkyrienskies-118-2.1.0-beta9.jar

**Comment by UrbanSide** [comment]
Delete Immersive Portals. Eureka(VS2) mod dont work with Immersive Portals.

**Comment by snag124** [comment]
hi I'm having the same problem but I don't have Immersive Portals
here is my mod list 

[1.16.5] SecurityCraft
v1.9.5ApexGunAddon-1.16.5-0.0.1.jar
appleskin-forge-mc1.16.x-2.4.0.jar
appliedenergistics2-8.4.7.jar
Architects-Palette-1.16.4-1.1.5.jar
architectury-1.32.66.jar
baubleyheartcanisters-1.16.5-1.1.11.jar
betterfpsdist-1.2.jar
blockcarpentry-1.16-0.4.1.jar
Bookshelf-Forge-1.16.5-10.4.33.jar
BotanyPots-1.16.5-7.1.39.jar
BotanyTrees-1.16.5-3.0.9.jar
BrandonsCore-1.16.5-3.0.15.248-universal.jar
BuildingWands_mc1.16.5-2.6.4_release-forge.jar
caelus-forge-1.16.5-2.1.3.2.jar
cfm-7.0.0pre22-1.16.3.jar
cgm-1.2.6-1.16.5.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chiselsandbits-1.0.63.jar
cloth-config-4.16.91-forge.jar
CodeChickenLib-1.16.5-4.0.7.445-universal.jar
cofh_core-1.16.5-1.5.2.22.jar
configured-1.5.3-1.16.5.jar
Controlling-7.0.0.28.jar
CookingForBlockheads_1.16.5-9.3.4.jar
craftable egg mod.jar
Craftable_NameTag 1.16.x.jar
Craftablespawner_v.1.0.jar
createaddition-1.16.5-20220129a.jar
create-mc1.16.5_v0.3.2g.jar
create-stuff-additions1.16.5_v1.1.6.jar
Croptopia-1.16.5-FORGE-2.0.5.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.0.8.2.jar
curiouselytra-forge-1.16.5-4.0.2.4.jar
Decoration Mod 1.6 (Ver 1.16.5).jar
decorative_blocks-1.16.4-1.7.2.jar
Draconic-Additions-1.16.5-2.2.3.6-universal.jar
Draconic-Evolution-1.16.5-3.0.27.462-universal.jar
Draconic-Machinery_1.0.0-Beta_1.16.5.jar
drinkbeer-1.16.5-2.3.5.jar
dynamiclights-1.16.5.1.jar
DynamicSurroundings-1.16.5-4.0.5.0.jar
Electrodynamics-1.16.5-0.5.0-2.jar
EnchantingInfuser-v1.0.2-1.16.5-Forge.jar
ender-quarry-plus-1.0.1-1.16.5.jar
engineersdecor-1.16.5-forge-1.1.19.jar
envirocore-1.16.5-3.0.9.3.jar
envirotech-1.16.5-3.0.9.4.jar
eureka-1.0.0-alpha7.jar
evsalcohol32.jar
ExtremeReactors2-1.16.5-2.0.60.jar
extremeSoundMuffler-3.18_1.16.5.jar
FastLeafDecay-v25.2.jar
FluxNetworks-1.16.5-6.2.1.14.jar
flywheel-1.16-0.2.5.jar
forge-branders-spawnermod-1.16.5-1.8.14.jar
FramedBlocks-2.16.2.jar
geckolib-forge-1.16.5-3.0.106.jar
Gun mod1.16.5.jar (mr.crayfishs)
Hwyla-forge-1.10.11-B78_1.16.2.jar
ImmersiveEngineering-1.16.5-5.1.0-148.jar
ImmersivePetroleum-1.16.5-3.4.0-13.jar
ImmersivePosts-1.16.5-4.3.0-1.jar
inventorypets-1.16.5-2.0.15.jar
invtweaks-1.16.4-1.0.1.jar
inzheFoPCore-v.1.2.0.jar
ironchest-1.16.5-11.2.21.jar
itdmtrct-1.16.5-1.0.3.jar
jei-1.16.5-7.7.1.153.jar
kotlinforforge-351264-3527736.jar
Lollipop-1.16.5-3.2.9.jar
Mantle-1.16.5-1.6.157.jar
mcw-bridges-2.0.6-mc1.16.5forge.jar
mcw-doors-1.0.7-mc1.16.5.jar
mcw-fences-1.0.7-mc1.16.5forge.jar
mcw-furniture-3.0.2-mc1.16.5.jar
mcw-lights-1.0.5-mc1.16.5forge.jar
mcw-paths-1.0.2forge-mc1.16.5.jar
mcw-roofs-2.2.2-mc1.16.5forge.jar
mcw-trapdoors-1.0.8-mc1.16.5forge.jar
mcw-windows-2.1.1-mc1.16.5forge.jar
Mekanism-1.16.5-10.1.2.457.jar
MekanismAdditions-1.16.5-10.1.2.457.jar
MekanismGenerators-1.16.5-10.1.2.457.jar
MekanismTools-1.16.5-10.1.2.457.jar
mob_grinding_utils-1.16.5-0.4.37.jar
morecfm-1.3.1-1.16.3.jar
MouseTweaks-2.14-mc1.16.2.jar
movingelevators-1.3.11-forge-mc1.16.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
Nuclear_Science-1.16.5-0.4.0-1.jar
obfuscate-0.6.3-1.16.5.jar
OptiFine_1.16.5_HD_U_G8.jar
OptiForge-MC1.16.5-0.5.7.jar
OreExcavation-1.8.157.jar
Patchouli-1.16.4-53.3.jar
Powah-1.16.5-2.3.16.jar
power1.3.jar
powerfulWeaponsOfWar1.6.7-1.16.5-Forge.jar
ProjectE-1.16.5-PE1.0.2.jar
PuzzlesLib-v1.0.15-1.16.5-Forge
quantum_quarry_plus-1.10.3.jar
RealisticSleep-1.16.5-1.3.5.64-universal.jar
redstone_arsenal-1.16.5-0.9.2b.5.jar
selene-1.16.5-1.9.0.jar
simplegens-1.16.5-3.0.9.2.jar
simpletomb-1.16.5-1.0.10.jar
Simply Spawners 1.16.5 v1.2.jar
sounddeviceoptions-1.4.3.jar
StevesQuarry-MCv1.16.5-v1.0.9.jar
StorageDrawers-1.16.3-8.5.2.jar
supermartijn642configlib-1.1.6-forge-mc1.16.jar
supermartijn642corelib-1.1.1-forge-mc1.16.jar
supplementaries-1.16.5-0.18.5.jar
swingthroughgrass-1.16.4-1.5.3.jar
TConstruct-1.16.5-3.3.4.335.jar
tesseract-1.0.28-forge-mc1.16.jar
thermal_expansion-1.16.5-1.5.2.16.jar
thermal_foundation-1.16.5-1.5.2.30.jar
thutcore-1.16.4-8.2.0.jar
thuttech-1.16.4-9.1.2.jar
TinyMobFarm-1.16.5-1.1.2.jar
torchmaster-2.3.8.jar
u_team_core-1.16.5-3.2.1.229.jar
useful_backpacks-1.16.5-1.12.1.103.jar
valkyrielib-1.16.5-3.0.9.5.jar
valkyrienskies-116-forge-2.0.0-alpha6+6626c148b0.jar
vehicle-mod-0.45.2-1.16.3.jar
wirelesschargers-1.0.7-forge-mc1.16.jar
Xaeros_Minimap_22.17.1_Forge_1.16.5.jar
XaerosWorldMap_1.28.7_Forge_1.16.5.jar
ZeroCore2-1.16.5-2.1.30.jar

**Comment by UrbanSide** [comment]
> hi I'm having the same problem but I don't have Immersive Portals here is my mod list
> 
> [1.16.5] SecurityCraft v1.9.5ApexGunAddon-1.16.5-0.0.1.jar appleskin-forge-mc1.16.x-2.4.0.jar appliedenergistics2-8.4.7.jar Architects-Palette-1.16.4-1.1.5.jar architectury-1.32.66.jar baubleyheartcanisters-1.16.5-1.1.11.jar betterfpsdist-1.2.jar blockcarpentry-1.16-0.4.1.jar Bookshelf-Forge-1.16.5-10.4.33.jar BotanyPots-1.16.5-7.1.39.jar BotanyTrees-1.16.5-3.0.9.jar BrandonsCore-1.16.5-3.0.15.248-universal.jar BuildingWands_mc1.16.5-2.6.4_release-forge.jar caelus-forge-1.16.5-2.1.3.2.jar cfm-7.0.0pre22-1.16.3.jar cgm-1.2.6-1.16.5.jar Chisel-MC1.16.5-2.0.1-alpha.4.jar chiselsandbits-1.0.63.jar cloth-config-4.16.91-forge.jar CodeChickenLib-1.16.5-4.0.7.445-universal.jar cofh_core-1.16.5-1.5.2.22.jar configured-1.5.3-1.16.5.jar Controlling-7.0.0.28.jar CookingForBlockheads_1.16.5-9.3.4.jar craftable egg mod.jar Craftable_NameTag 1.16.x.jar Craftablespawner_v.1.0.jar createaddition-1.16.5-20220129a.jar create-mc1.16.5_v0.3.2g.jar create-stuff-additions1.16.5_v1.1.6.jar Croptopia-1.16.5-FORGE-2.0.5.jar CTM-MC1.16.1-1.1.2.6.jar curios-forge-1.16.5-4.0.8.2.jar curiouselytra-forge-1.16.5-4.0.2.4.jar Decoration Mod 1.6 (Ver 1.16.5).jar decorative_blocks-1.16.4-1.7.2.jar Draconic-Additions-1.16.5-2.2.3.6-universal.jar Draconic-Evolution-1.16.5-3.0.27.462-universal.jar Draconic-Machinery_1.0.0-Beta_1.16.5.jar drinkbeer-1.16.5-2.3.5.jar dynamiclights-1.16.5.1.jar DynamicSurroundings-1.16.5-4.0.5.0.jar Electrodynamics-1.16.5-0.5.0-2.jar EnchantingInfuser-v1.0.2-1.16.5-Forge.jar ender-quarry-plus-1.0.1-1.16.5.jar engineersdecor-1.16.5-forge-1.1.19.jar envirocore-1.16.5-3.0.9.3.jar envirotech-1.16.5-3.0.9.4.jar eureka-1.0.0-alpha7.jar evsalcohol32.jar ExtremeReactors2-1.16.5-2.0.60.jar extremeSoundMuffler-3.18_1.16.5.jar FastLeafDecay-v25.2.jar FluxNetworks-1.16.5-6.2.1.14.jar flywheel-1.16-0.2.5.jar forge-branders-spawnermod-1.16.5-1.8.14.jar FramedBlocks-2.16.2.jar geckolib-forge-1.16.5-3.0.106.jar Gun mod1.16.5.jar (mr.crayfishs) Hwyla-forge-1.10.11-B78_1.16.2.jar ImmersiveEngineering-1.16.5-5.1.0-148.jar ImmersivePetroleum-1.16.5-3.4.0-13.jar ImmersivePosts-1.16.5-4.3.0-1.jar inventorypets-1.16.5-2.0.15.jar invtweaks-1.16.4-1.0.1.jar inzheFoPCore-v.1.2.0.jar ironchest-1.16.5-11.2.21.jar itdmtrct-1.16.5-1.0.3.jar jei-1.16.5-7.7.1.153.jar kotlinforforge-351264-3527736.jar Lollipop-1.16.5-3.2.9.jar Mantle-1.16.5-1.6.157.jar mcw-bridges-2.0.6-mc1.16.5forge.jar mcw-doors-1.0.7-mc1.16.5.jar mcw-fences-1.0.7-mc1.16.5forge.jar mcw-furniture-3.0.2-mc1.16.5.jar mcw-lights-1.0.5-mc1.16.5forge.jar mcw-paths-1.0.2forge-mc1.16.5.jar mcw-roofs-2.2.2-mc1.16.5forge.jar mcw-trapdoors-1.0.8-mc1.16.5forge.jar mcw-windows-2.1.1-mc1.16.5forge.jar Mekanism-1.16.5-10.1.2.457.jar MekanismAdditions-1.16.5-10.1.2.457.jar MekanismGenerators-1.16.5-10.1.2.457.jar MekanismTools-1.16.5-10.1.2.457.jar mob_grinding_utils-1.16.5-0.4.37.jar morecfm-1.3.1-1.16.3.jar MouseTweaks-2.14-mc1.16.2.jar movingelevators-1.3.11-forge-mc1.16.jar NaturesCompass-1.16.5-1.9.1-forge.jar Nuclear_Science-1.16.5-0.4.0-1.jar obfuscate-0.6.3-1.16.5.jar OptiFine_1.16.5_HD_U_G8.jar OptiForge-MC1.16.5-0.5.7.jar OreExcavation-1.8.157.jar Patchouli-1.16.4-53.3.jar Powah-1.16.5-2.3.16.jar power1.3.jar powerfulWeaponsOfWar1.6.7-1.16.5-Forge.jar ProjectE-1.16.5-PE1.0.2.jar PuzzlesLib-v1.0.15-1.16.5-Forge quantum_quarry_plus-1.10.3.jar RealisticSleep-1.16.5-1.3.5.64-universal.jar redstone_arsenal-1.16.5-0.9.2b.5.jar selene-1.16.5-1.9.0.jar simplegens-1.16.5-3.0.9.2.jar simpletomb-1.16.5-1.0.10.jar Simply Spawners 1.16.5 v1.2.jar sounddeviceoptions-1.4.3.jar StevesQuarry-MCv1.16.5-v1.0.9.jar StorageDrawers-1.16.3-8.5.2.jar supermartijn642configlib-1.1.6-forge-mc1.16.jar supermartijn642corelib-1.1.1-forge-mc1.16.jar supplementaries-1.16.5-0.18.5.jar swingthroughgrass-1.16.4-1.5.3.jar TConstruct-1.16.5-3.3.4.335.jar tesseract-1.0.28-forge-mc1.16.jar thermal_expansion-1.16.5-1.5.2.16.jar thermal_foundation-1.16.5-1.5.2.30.jar thutcore-1.16.4-8.2.0.jar thuttech-1.16.4-9.1.2.jar TinyMobFarm-1.16.5-1.1.2.jar torchmaster-2.3.8.jar u_team_core-1.16.5-3.2.1.229.jar useful_backpacks-1.16.5-1.12.1.103.jar valkyrielib-1.16.5-3.0.9.5.jar valkyrienskies-116-forge-2.0.0-alpha6+6626c148b0.jar vehicle-mod-0.45.2-1.16.3.jar wirelesschargers-1.0.7-forge-mc1.16.jar Xaeros_Minimap_22.17.1_Forge_1.16.5.jar XaerosWorldMap_1.28.7_Forge_1.16.5.jar ZeroCore2-1.16.5-2.1.30.jar

Yes,but you have OptiFine,delete it)

**Comment by snag124** [comment]
nope that didn't work I completely removed Opti fine and Opti forge and its sadly still invisible the ship will fly and turn but only the steering wheel is visible (not the base of the block just the wheel). even tried uninstalling Valkyrie skies and eureka and reinstalling them didn't change. As a last resort I tried using it on its own and it works just fine so I know its one of my mods i just don't know which one.

**Comment by tessitalisman** [comment]
Blockface Culling needs to be turned off

**Comment by HitmonGabe** [comment]
@tessitalisman Where do I turn this setting off?

**Comment by Optionalpoop** [comment]
I had a similar issue without Optifine or Immersive Portals. What ended up working was installing Embeddium and disabling Blockface Culling in its advanced settings. AFAIK it is not possible to turn off Blockface Culling without mods adding the setting.

**Comment by jesper1425** [comment]
> I had a similar issue without Optifine or Immersive Portals. What ended up working was installing Embeddium and disabling Blockface Culling in its advanced settings. AFAIK it is not possible to turn off Blockface Culling without mods adding the setting.


i don't have the blockface culling option with embedium installed it only has: 

use presistent mapping and cpu render-ahead limit3 frames

so yea hope you can help
