### ISSUE TITLE
Bed on ship

### ISSUE THREAD

**Issue by Filetio** [ValkyrienSkies/Eureka#126]
when having a bed on ship and tring to sleep in it i'm geting teleported god knows where since nothing loads and coordinates are showing xyz:-28669941/91/1229053 or other realy high numbers, same thing happens when respawning after death sometimes there is broken parts of ship where when i right click on broken helm im geting teleported to right ship position i have other mods but same things happends when i had only eureka instaled 
but just in case:
-Ars creo
-Ars nouveau
-Create
-Courios API
-Flywheel
-HT's TreeChop
-JEI
-Kotlin for forge
-Patchouli
-Valkyrien skies 2
-VS Eureka

**Comment by Filetio** [comment]
nvm just updated to beta6 and its working fine

**Comment by Ch1216** [comment]
You can also update to beta 10, and it will work, they fixed it
