### ISSUE TITLE
boat turns invisible when assembled on 1.18.2

### ISSUE THREAD

**Issue by ArthusMachima** [ValkyrienSkies/Eureka#127]
hitboxes were only visible
![image](https://user-images.githubusercontent.com/123818551/215271741-f4166eb7-2bd8-41ea-8efa-340061fab986.png)

mod list: 
![image](https://user-images.githubusercontent.com/123818551/215271650-22a8b003-ef90-420b-ad87-934de223f45b.png)

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative

**Comment by ArthusMachima** [comment]
ohh that's why

thanks
