### ISSUE TITLE
Interesting bug when destroying ships.

### ISSUE THREAD

**Issue by ABradyK** [ValkyrienSkies/Eureka#129]
Recently found a bug where if you remove all blocks on an assembled ship except for the helm while still riding the ship and then destroy the helm, you get teleported to -28645264.500, {current Y level,} 12290052.500.

Recreation:
Step 1: create a valid ship.

Step 2: Destroy all of the ship except for the helm while still riding it.

Step 3: Destroy the helm while still riding it.

Result: You get teleported to -28645264.500, {current Y level,} 12290052.500.

**Comment by Rubydesic** [comment]
dupe of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/307
