### ISSUE TITLE
Assembling a ship over the ocean freezes the game

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Eureka#13]
Water, lava, netherrack, and several other blocks should be in the default configuration for natural blocks.
Tested on Fabric.

Perhaps a cleaner solution is in order? Mods have in the past kept track of what blocks are naturally generated.

**Comment by ewoudje** [comment]
Quick fix for milestone; would be making the config complete, make pr's

**Comment by copperwarrior** [comment]
Closing because original issue is fixed. Making new issue for cleaner solution.
