### ISSUE TITLE
Missing refmap in 1.18.2 fabric beta 6

### ISSUE THREAD

**Issue by CodeF53** [ValkyrienSkies/Eureka#131]
Reference map 'eureka-fabric-refmap.json' for vs_eureka.mixins.json could not be read. If this is a development environment you can ignore this message

**Comment by Rubydesic** [comment]
If it doesn't cause an issue no problem. If it does make a new issue and upload the complete log and not just some random part

**Comment by CodeF53** [comment]
Its a huge issue because none of your mixins work because of it and the game crashes on ship assembly with the build.

**Comment by CodeF53** [comment]
I am very used to this error breaking everything as it means mixins for the file it mentions won't work, but shockingly your mod works fine with it.
I saw it and instantly assumed it was responsible for horrible crashes, sorry.
