### ISSUE TITLE
Conflict with Very Many Players: Can't Pilot Ship.

### ISSUE THREAD

**Issue by CodeF53** [ValkyrienSkies/Eureka#132]
Without VMP, can pilot fine, with, cant pilot.
[log](https://paste.atlauncher.com/view/017998be-2849-404f-825e-de58b74eb2d2)

https://user-images.githubusercontent.com/37855219/216229018-0378ad62-77fa-4070-a871-cdede1e189af.mp4

Steps to recreate:
1. have ValkyrienSkies, Eureka, required dependencies, and VMP installed.
2. create and assemble ship
3. attempt to take the wheel

**Comment by Rubydesic** [comment]
Fixed in latest VMP
