### ISSUE TITLE
After a time, my airship stops working.

### ISSUE THREAD

**Issue by ismaltion** [ValkyrienSkies/Eureka#134]
You see if i create a airship it works well, however after a time, while i'm driving, the steering wheel stops working and i can't pilot the airship. I lost hours of work because of this issue and it's happening since the firsts versions. It never got fixed.

**Comment by walksanatora** [comment]
are you sure you aren't pressing the cruise controll button on accident

**Comment by thecreare** [comment]
The physics engine might have also crashed, try reloading the world.

**Comment by walksanatora** [comment]
is this SP or MP
because if it is MP and only happening to you, it would probally be CruiseControll (or align)
if it is SP, it is a major bug that no one has found

**Comment by ismaltion** [comment]
what's that?

**Comment by ismaltion** [comment]
How i do that?

**Comment by ismaltion** [comment]
it's multiplayer aternos

**Comment by ismaltion** [comment]
nevermind it was cruise controll, thanks for making me know, an airship was
saved.
