### ISSUE TITLE
Half of my ship goes down by one block when I deconstruct

### ISSUE THREAD

**Issue by operator201** [ValkyrienSkies/Eureka#136]
I am currently using ValkiyrienSkies (forge-2.0.0-alpha6) and Eureka (1.0.0-alpha7) and sometimes when I deconstruct a ship, half of it goes down or up by one block(see picture below). After some testing I fugured out that it mostly happens when the ship faces y-axis.

![ship stuck](https://user-images.githubusercontent.com/124353824/216812204-bc7af4d2-f88c-4623-8338-fffa54b28a7f.png)

**Comment by Rubydesic** [comment]
The fix for this issue has already been pushed and will be part of the next Curseforge release.
