### ISSUE TITLE
Minecraft Crashes On Startup

### ISSUE THREAD

**Issue by Justice603-tech** [ValkyrienSkies/Eureka#139]
**Apparently** Running tlauncher with my modpack: Throw Create To The Skies!  with create in it crashes my minecraft
## My Logs
[crash-2023-02-05_18.58.04-client.txt](https://github.com/ValkyrienSkies/Eureka/files/10611149/crash-2023-02-05_18.58.04-client.txt)

**Comment by Rubydesic** [comment]
has nothing to do with eureka or vs2
