### ISSUE TITLE
1.18.2 crash

### ISSUE THREAD

**Issue by Igilq** [ValkyrienSkies/Eureka#140]
I wanted to launch minecraft with kotlin, eureka and valerien skies but it crashes when i want to launch minecraft. I attached latest .log file.
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/10611295/latest.log)

**Comment by ANDREICALOIANU** [comment]
Me too

**Comment by Rubydesic** [comment]
Update forge

**Comment by ANDREICALOIANU** [comment]
doesn't seem to work

**Comment by ANDREICALOIANU** [comment]
if you need it, here's my latest .log
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/10611705/latest.log)

**Comment by Igilq** [comment]
I have latest version of forge installed

**Comment by ANDREICALOIANU** [comment]
yeah, exactly
