### ISSUE TITLE
Eureka and ValkSkies2 crashing on startup [server]

### ISSUE THREAD

**Issue by Xplodin** [ValkyrienSkies/Eureka#147]
https://gist.github.com/Xplodin/6e2b528fdc487c6259b366af631f5d5c

crashed on boot.
After server crashed while spamming "too many physics frames in the queue, is the game stage broken"
Modpack:
BeanPack: Refried 92R

**Comment by Rubydesic** [comment]
Update to the latest version of VS2 and/or Eureka on Curseforge

**Comment by Xplodin** [comment]
issue persists on latest update.

**Comment by Rubydesic** [comment]
Make a new issue and post the log after updating both mods
