### ISSUE TITLE
Blocks turn invisible when assembling (OptiFine Confliction)

### ISSUE THREAD

**Issue by savagechick3n** [ValkyrienSkies/Eureka#148]
After much pruning, I have discovered that the 1.18.2 version of OptiFine conflicts with Eureka in such a way that all blocks turn invisible when assembled. If anyone else has had this issue, I suggest disabling OptiFine for now until/if the mod developers fix it.

**Comment by savagechick3n** [comment]
Also, to be noted, I have completely singled it out; when using base Eureka, Kotlin and ValkyrienSkies (the requirements) with OptiFine, this occurs. It is not a confliction of multiple mods, it is entirely OptiFine and either Eureka, ValkyrienSkies, or Kotlin being incompatible. I also tried it with multiple versions of all three Kotlin, Eureka and ValkyrienSkies. The issue persists in all 1.18.2 verisons.

**Comment by Rubydesic** [comment]
This is known and will not be fixed VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative

**Comment by savagechick3n** [comment]
> This is known and will not be fixed VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative

I see, thank you for your time.
