### ISSUE TITLE
ships vanish upon assembly

### ISSUE THREAD

**Issue by Mikecolle** [ValkyrienSkies/Eureka#150]
after assembling a ship the whole build just vanishes, the blocks can be seen in oneprobe/waila but they are ghost blocks

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative
