### ISSUE TITLE
Game crashes when placing helm

### ISSUE THREAD

**Issue by SmokeyVrtX** [ValkyrienSkies/Eureka#157]
![image-2](https://user-images.githubusercontent.com/125857927/220432062-7436cf77-5cd2-46d7-9d5d-9bd5191ece02.png)
Accidentally closed the ticket re-uploaded, when I place the helm it crashes gives that error code, then when I load back in the helm isn't there or in my inventory it will also crash if I look up helms in JEI

**Comment by walksanatora** [comment]
you ... could just have asked to re-open it...
also what eureka version you on

**Comment by SmokeyVrtX** [comment]
Lmao decide to just remake it all at once I'm on latest of both I'm pretty
sure, valk is 118-2.1.0-beta.10 and eureka-1.1.0-beta.8

**Comment by SmokeyVrtX** [comment]
It's ok I'm dumb lmao

**Comment by walksanatora** [comment]
eureka beta 9: *exist*

**Comment by SmokeyVrtX** [comment]
Must've updated yesterfuckingday

**Comment by SmokeyVrtX** [comment]
Either way I got it to work by changing to rubidium instead of optifine
