### ISSUE TITLE
Ship vanishing completely when trying to assemble 

### ISSUE THREAD

**Issue by Friasoaple** [ValkyrienSkies/Eureka#160]
Whenever I try to assemble a ship it completely vanishes instead of applying the physics?

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative
