### ISSUE TITLE
max angular speed

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Eureka#167]
Large ships can turn painfully slowly, since angular velocity is determined by the diameter of the ship. Even though this makes sense, it's not really nice for gameplay. There should be a max angular speed, maybe ~36deg/s so that it can't take longer than 10 seconds to 360 your ship, no matter how large.

**Comment by walksanatora** [comment]
might i suggest making this a option to set
1. the max angular speed
2. the minimum angular speed
(and mabey other options to determine how it eases between the two values)
