### ISSUE TITLE
can't compile the mod. Help me pls :D

### ISSUE THREAD

**Issue by Jancpot** [ValkyrienSkies/Eureka#179]
Error: 
* Where:
Build file 'C:\Users\jancp\OneDrive\������� ����\����� ����� (14)\����� �����\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'vs-eureka-mod'.
> begin 0, end 10, length 0

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 14s

Code:
} else {
    String gitRevision = "git rev-parse HEAD".execute().text.trim()

    version = eureka_version + '+' + gitRevision.substring(0, 10)
}

File_Name: build.gradle
![Screenshot_11](https://user-images.githubusercontent.com/83835751/230458128-53b22034-fa36-4612-8d8a-df0ac5f2c791.png)

**Comment by redmine4404** [comment]
Can you send all the logs pls ?

**Comment by Rubydesic** [comment]
checkout the repository using git and make sure you have git installed
