### ISSUE TITLE
Invisible ships using Ribidium

### ISSUE THREAD

**Issue by CaptainLack** [ValkyrienSkies/Eureka#183]
I've went through my mod list to find out that ribidium is causing this rendering issue and found that any version of ribidium I use causes this issue. 

I've reset my configs each time I removed a mod to find this.
I think its funny. Any reason this would be an issue?
 Im using version 1.18.2

**Comment by walksanatora** [comment]
did you mean: Rubidium

**Comment by SpyingGnome775** [comment]
Optifine can cause this
