### ISSUE TITLE
Block orientation not respected when disassembling a ship

### ISSUE THREAD

**Issue by unmoving-javi** [ValkyrienSkies/Eureka#185]
(I checked briefly to see if this issue has already been posted, but I only used the search bar, so it's possible this is a duplicate. Apologies if so.)

When a ship is assembled with a block that has an 'orientation' (such as the ship helm or a bed), turning the ship 90 degrees and disassembling it will result in all oriented blocks returning to their _original_ orientation, which no longer matches up with the ship.

As an example: The two individual blocks of a bed will remain facing north-south if originally placed this way, even if the ship is rotated to face east-west. This can be fixed by reassembling the ship and rotating it again, but that seems a little bit silly.

The expected behavior would be the blocks being rotated to match the change in the ship's change in orientation from its original assembly point.

[This is usually represented as a 'facing' or 'axis' block tag. This doesn't appear to be an issue for logs, for whatever reason, but this is still an issue with stairs, for example. This does not seem to affect things that face upwards or downwards.]

**Comment by unmoving-javi** [comment]
Bizarrely, I cannot seem to replicate this now that it's happened. I've rebuilt my ship to the exact same specifications but for the life of me I can't get it to work.

It may be because I disassembled before aligning, or might be something to do with a movement key being input to rotate the ship as it disassembled.

**Comment by unmoving-javi** [comment]
Some basic experimentation later and it seems like it might have something to do with the original chunk the ship was in being unloaded, but this is HEAVY speculation, I really have no clue.

**Comment by walksanatora** [comment]
very-old and long-known issue
planned on being fixed "eventually" aka: when they have nothing better to do

**Comment by Ramelstag** [comment]
If you assemble pointing, for instance, north, and then at some point later on, disassemble pointing east, it will bug out and rotate blocks like stairs, fences, and what not

if you do that again, disassembling pointing north since you assembled pointing east _( north again because the helm has rotated. aka, just point to the right-most direction)_ (90° clockwise/to the right) will actually fix itself!
