### ISSUE TITLE
unable to assemble ship

### ISSUE THREAD

**Issue by Solow2496** [ValkyrienSkies/Eureka#188]
I placed the helm and went to assemble the ship and it told me to sneak to do so. sneaking+right click picks up the helm to move it instead of opening the menu. i looked in the "key binding" tab under the "controls" setting and could not fix this as there was no category for the mod's key bindings. i am using Minecraft 1.18.2 Fabric edition.

**Comment by doduck13** [comment]
then change the keybind for picking up blocks

**Comment by Solow2496** [comment]
> then change the keybind for picking up blocks

Okay so i found the key bind but now i'm just stuck on an invisible ship with no way to move myself off. RIP my world

**Comment by Rubydesic** [comment]
remove optifine and add eureka helm to carry-on blacklist
