### ISSUE TITLE
Burner blocks eat too much coal

### ISSUE THREAD

**Issue by StewStrong** [ValkyrienSkies/Eureka#19]
Sometimes they consume everything inside them. Very sus.

**Comment by copperwarrior** [comment]
Couldn't replicate this issue on latest commit. Replication steps?

**Comment by Rubydesic** [comment]
Put a stack of coal blocks into the engine and take them out and put them back in repeatedly, and the stack eventually disappears

**Comment by StewStrong** [comment]
Lol I forgot to close this after I fixed this issue 😂
