### ISSUE TITLE
Invicible transport

### ISSUE THREAD

**Issue by Turanus5966** [ValkyrienSkies/Eureka#201]
Why my transport invicible?

Eureka! 1.1.0 1.18.2

**Comment by Rubydesic** [comment]
VS2 1.18+ is incompatible with Optifine. Consider using [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) as an alternative
