### ISSUE TITLE
Missing config for linearStabilizeMaxAntiVelocity while helm is being used.

### ISSUE THREAD

**Issue by millennIumAMbiguity** [ValkyrienSkies/Eureka#204]
When linearStabilizeMaxAntiVelocity is set to 0, you can leave the helm and still travel.
But while holding the helm, I need to hold down W to move and when I release the W key, I instantly stop.

**Comment by Woodynson** [comment]
i have the same problem does anyone know why is it doing this ? or how to fix it ? every time i click assemble the blocks just vanish

**Comment by 301haru** [comment]
same issue, turn speed affects but forward movement does not. It only affects when you're not on the helm, it can be tested if you press W and instantly quit helm.

**Comment by millennIumAMbiguity** [comment]
Duplicate of #105
But explains how linearStabilizeMaxAntiVelocity currently works.
