### ISSUE TITLE
Ship doesn't appear when built

### ISSUE THREAD

**Issue by LilacStarvix** [ValkyrienSkies/Eureka#223]
### Minecraft Version

1.19.2

### Mod Loader

Forge

### Issue description

When I build the ship, the blocks simply disappear when I build the ship, leaving me stuck unable to move inside an entity. 

### Issue reproduction

build a ship and use the hull, easy as.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/11751874/latest.log)

**Comment by MAGNUMgame** [comment]
same problem

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS, addons, and re-open the issue
