### ISSUE TITLE
<Servers Self Shutoff After Awhile>

### ISSUE THREAD

**Issue by SpyingGnome775** [ValkyrienSkies/Eureka#234]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

I Get quite far in the game then after a bit the server doent crash just shuts off and everytime i turn it back on you can play for like 2 min and it just shuts down agene

### Issue reproduction

use aternos server hosting then just servive and make a airship then after a while thit will eventualy happen

**Comment by NullHarp** [comment]
thats not a bug, aeternos is not powerful enough to handle vs2, only solution to my knowledge is to just not use free hosting such as aternos

**Comment by Miszelka** [comment]
> thats not a bug, aeternos is not powerful enough to handle vs2, only solution to my knowledge is to just not use free hosting such as aternos

So, the mod will probably never be able to run on aternos servers?

**Comment by walksanatora** [comment]
for free hosting I would have to reccommend minehut or ... whats that one with the blue cube logo
