### ISSUE TITLE
Lost ship, any way to locate it?

### ISSUE THREAD

**Issue by arand4** [ValkyrienSkies/Eureka#240]

**Comment by Slipfar** [comment]
Could try using tp @v[limit=1] which managed to teleport me to one of the airships on my server, but I have no idea how to go to specific ships cuz theres no documentation.

**Comment by walksanatora** [comment]
you should get the slug of your ships, from there you can /tp @v[slug="correct-horse-battery-staple"]

**Comment by arand4** [comment]
Sorry, I though I had closed the thread, I contacted the discord and
already got the situation solved.
Thanks for the reply anyway.
