### ISSUE TITLE
minecraft:pink_petals is not blacklisted by default

### ISSUE THREAD

**Issue by ghost** [ValkyrienSkies/Eureka#245]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

minecraft:pink_petals is not blacklisted by default

### Issue reproduction

minecraft:pink_petals is not blacklisted by default

**Comment by millennIumAMbiguity** [comment]
duplicate of #229

also, [Pink Petals](https://minecraft.fandom.com/wiki/Pink_Petals) was added in Minecraft 1.20.
