### ISSUE TITLE
Eureka 1.19.2 does not work with all three versions of VS 1.19.2

### ISSUE THREAD

**Issue by Obidede98** [ValkyrienSkies/Eureka#254]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Fabric

### Issue description

When I try to open Minecraft with Eureka, it crashes. Everything else works together without Eureka. Valkyrien Skies, Fabric, etc. loads fine without Eureka. But only when I use Eureka, does it crash.

I downloaded the Eureka Ships Mod with Valkyrien Skies along with all the respective dependency mods (cloth-config, fabric), all for 1.19.2. 

I was able to open Minecraft with all the mods when I excluded Eureka Ships, so I know it has something to do with that mod in particular.

There is one version of Eureka for 1.19.2 [eureka-1192-1.2.0-beta.1.jar] and 3 versions of Valkyrien Skies for 1.19.2 [valkyrienskies-1192-2.2.0-beta.1.jar;        ...beta.2.jar;      ...beta.1.jar]. I have tried all 3 combinations and each yields a crash.

Minecraft gave me the message:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'vs_eureka'!

The Crash Report is included as a text file,
An image of the downloaded mod files is included.

Thank you all so much for all that you do. I hope be to play this one day.

[crash-2023-09-09_15.55.53-client.txt](https://github.com/ValkyrienSkies/Eureka/files/12566585/crash-2023-09-09_15.55.53-client.txt)

![image](https://github.com/ValkyrienSkies/Eureka/assets/144556383/73f0e6e6-1445-4dda-b6b3-9a6245b7a45a)

### Issue reproduction

Download files:
[fabric-api-0.62.0+1.19.2]
[cloth-config-8.2.88-fabric.jar]
[eureka-1192-1.2.0-beta.1.jar]
[valkyrienskies-1192-2.2.0-beta.3.jar]

Open Minecraft Launcher
Click Play

![image](https://github.com/ValkyrienSkies/Eureka/assets/144556383/191220b8-6bab-4958-9147-acd3eaec22b4)

### Logs

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/12566578/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Eureka/files/12566579/debug.log)

**Comment by StewStrong** [comment]
It works on my machine /shrug.

Try updating your fabric api to at least `fabric-api-0.76.0+1.19.2`
