### ISSUE TITLE
Server crash while on airship causes weird issues

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Eureka#275]
I was flying my airship when the server I was on crashed. I joined later and the server was lagging severely and xp was flying out of where the ship would've been. The server owner restarted, and my airship reappeared in a chunk a few chunks back which I had been flying through. The xp was now obtainable. I have no idea what happened, the issue happened multiple times. The server seems to think you're where the xp is and will place you back every time you relog.

https://github.com/ValkyrienSkies/Eureka/assets/101488091/da18dfef-33c6-43d6-adf4-37afccb0cbc2

**Comment by Rubydesic** [comment]
Please make a new issue and follow the issue template, providing all the required information. Make sure that you test with at most one other mod besides Valkyrien Skies and addons.

**Comment by AlexanderwithaA** [comment]
It wasn’t a crash that caused the issue but a forced server restart
