### ISSUE TITLE
Achor effect doesn't stop when redstone deactivates or when the anchor is removed, ship is permanently stuck

### ISSUE THREAD

**Issue by ArthurHenriqueCota** [ValkyrienSkies/Eureka#279]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Once activated the anchor effect won't go away by any means, turning off redstone and breaking the anchor does nothing.
It also prevents aligning/disassembling of the ship.

I tested multiple times using only VS2 and Eureka.

### Issue reproduction

Make a ship
Add an anchor
Turn it on
Try to turn it off or break it
happens even if you turn it with a button or means other than a lever

**Comment by WULI610** [comment]
same problem in 1.19.2

**Comment by Trigger225** [comment]
1.20.1, still present and easily reproduced.

**Comment by talayawhite** [comment]
1.20.1 Additionally:
When trying to fix the ship by doing things like adding/removing the helm, I managed to fling myself and the ship very very far away. Maybe to where the ship really lives? Unsure.

Is there any way to get it back home? Can I edit a file somewhere to change the coordinates maybe? Even if it doesn't work anymore, I would like to have it back.
How advisable is using something like world edit to copy/paste it somewhere? EDIT: WorldEdit No. Structurize making and pasting a schematic yes!!

**Comment by ondekikeci** [comment]
I have a similar problem its in 1.20.1. I have 3 boats and I have a anchor in one of them I usually put it on I just downloaded the latest version of the mod and now two of my boats are not moving maybe its bc of the anchor bug but ıdk why the other one not moving (1 boat have anchor and not moving ıdk why, 1 boat dont have anchor not moving ıdk why, 1 boat dont have anchor and moving) if anyone know how to fix it pls help

**Comment by millennIumAMbiguity** [comment]
Works on my machine

https://github.com/ValkyrienSkies/Eureka/assets/37588844/9763c8a7-1b5d-4e33-89cc-18d766d602e7

**Comment by Deno-V** [comment]
Same problem. However I am using 1.20.1 with fabric. Is there any solution? Is this a bug?

**Comment by millennIumAMbiguity** [comment]
I'm going to close this issue as it is confirmed to work in main. (1.18)
There has not been a new release in a while. (feel free to build from main and try it out.)
note that changes in man will be merged into newer versions.
