### ISSUE TITLE
Game crashed on an older version of forge

### ISSUE THREAD

**Issue by JonnyWumpus** [ValkyrienSkies/Eureka#28]
Forge 1.16.5 version 36.2.39

A ship was burning. I moved away from it, placed a block, game crashed. 

Crash report:
[message (2).txt](https://github.com/ValkyrienSkies/Eureka/files/9896739/message.2.txt)

**Comment by Rubydesic** [comment]
fixed in c8b2b0cc962edc02cf7289f98750c1d3638deb79
