### ISSUE TITLE
Crash on Startup Forge 1.20.1 Latest CF Release 1.3.0-beta.2

### ISSUE THREAD

**Issue by HoodBlah** [ValkyrienSkies/Eureka#280]
### Mod Name

Unknown

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Game does not launch when Valkyrian Skies 2 is installed.

### Issue reproduction

[Ex.zip](https://github.com/ValkyrienSkies/Eureka/files/13710638/Ex.zip)
This is the modpack I am using. Is is centered around create.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Eureka/files/13710646/debug.log)
[debug(NoEureaka).log](https://github.com/ValkyrienSkies/Eureka/files/13710647/debug.NoEureaka.log)
[latest(NoEureka).log](https://github.com/ValkyrienSkies/Eureka/files/13710648/latest.NoEureka.log)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13710649/latest.log)

**Comment by Rubydesic** [comment]
The issue tracker is not for debugging your modpack
