### ISSUE TITLE
1.20.1 Optifine Support (Please Read)

### ISSUE THREAD

**Issue by Dr-Tahmasbi** [ValkyrienSkies/Eureka#282]
### Mod Name

Optifine

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

I know that it clearly mentions not to create issues related to optifine, but i just want to know if Eureka will ever support optifine? Or if there is an ETA? Im not sure. Any answers are appriciated.

### Issue reproduction

Using optifine.

**Comment by Rubydesic** [comment]
There is no ETA. We will not support Optifine. Use Sodium/Rubidium instead
