### ISSUE TITLE
Crash when trying to create a ship

### ISSUE THREAD

**Issue by vivagabe** [ValkyrienSkies/Eureka#286]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

When shift rightclick the helm to create a ship, the game crashes.

### Issue reproduction

Shift right clicking helm causes crash.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13800726/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Eureka/files/13800727/debug.log)

**Comment by Rubydesic** [comment]
Make sure to update vs2 and eureka to the latest version for 1.19

**Comment by vivagabe** [comment]
That fixed the issue. thank you!
