### ISSUE TITLE
minecraft crash on openning inventory on fabric 1.20.1, error: Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka

### ISSUE THREAD

**Issue by sidlo01** [ValkyrienSkies/Eureka#289]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

It happened first when I added it into modpack, so I decided for testing to create new clean profile with following:
Fabric 1.20.1 - 0.15.3
Fabric API 0.91.0
Valkyrien skies 2.1.3 Beta 1
Eureka 1.3.0 beta 3

Crash happens right away after opening inventory with crash:
java.lang.IllegalStateException: Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka

### Issue reproduction

on Curseforge:

1. Create new profile with MC version 1.20.1 Fabric 0.15.3
2. install Valkyrian skies
3. install Eureka
4. Launch and create singleplayer, open inventory in creative

### Logs

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13806554/latest.log)
[crash-2024-01-02_01.51.27-client.txt](https://github.com/ValkyrienSkies/Eureka/files/13806555/crash-2024-01-02_01.51.27-client.txt)

**Comment by sidlo01** [comment]
also tested with fabric 0.14.25, same result
When I removed eureka, worked fine.

**Comment by TroubledZorua** [comment]
Im having the same issue, I thought it was because I added create: interactive though. I decided Create: Interactive over Eureka

**Comment by GameBurrow** [comment]
Related to https://github.com/ValkyrienSkies/Eureka/issues/288

**Comment by sidlo01** [comment]
with update [Fabric 1.20.1] v1.3.0-beta.4 problem didnt happen again, seems fixed so I am closing this thread
