### ISSUE TITLE
wrong block model used for the wheel

### ISSUE THREAD

**Issue by Estebanmister** [ValkyrienSkies/Eureka#29]
1.16.5 forge 36.2.22 and 36.2.39, only VS2, Eureka and Create are installed
Animation of the "wheel" moving seems to work

![image](https://user-images.githubusercontent.com/36859022/198900036-9df363fe-fede-4d4b-94fa-1c3e2d2443a8.png)

After reloading resourcepacks:

![image](https://user-images.githubusercontent.com/36859022/198900050-178c7304-34b7-4d64-abcf-93de1d6cbde0.png)

**Comment by Rubydesic** [comment]
should be fixed in latest dev version
