### ISSUE TITLE
Ship doesnt move.

### ISSUE THREAD

**Issue by Diavol39** [ValkyrienSkies/Eureka#291]
### Eureka! Valkyrien Skyes 2

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

When i assemble my ship it floats but it doesnt move like it didnt assemble

### Issue reproduction

I dont know if it can be reproduced

### Logs

[2024-01-02-2.log.gz](https://github.com/ValkyrienSkies/Eureka/files/13813249/2024-01-02-2.log.gz)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
