### ISSUE TITLE
Can't pull items from ship engine on Fabric 1.20.1

### ISSUE THREAD

**Issue by RabbyDevs** [ValkyrienSkies/Eureka#300]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

![image](https://github.com/ValkyrienSkies/Eureka/assets/67389402/4a69bfdc-3e0a-4b74-8673-2e9127ba7143)
![image](https://github.com/ValkyrienSkies/Eureka/assets/67389402/ae6bdcc5-d8f4-49de-a1a7-1b8426024125)

### Issue reproduction

- Place a ship engine.
- Place a bucket of lava, try to place a hopper underneath.
Expected Behavior: The hopper pulls the empty bucket/bucket of lava.
Actual Behavior: The hopper did not pull the empty bucket.

This applies to modded things aswell.

**Comment by millennIumAMbiguity** [comment]
fixed in #301
