### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Crafty1340** [ValkyrienSkies/Eureka#302]
Eureka crashes with the Mod Pack 'BMC4', it's not a compatibility issue because I have Rubidium for 1.19.2 and it doesn't crash. I'm using 1.20.1 Forge 47.2.17. But the Mod pack has over 100 mods and I don't have time to look through all of them. also no crash report because it's the damn crash code of '1'! Also the Mod pack has Archetechtury (sorry for mis-spelling), Kotlin, Cloth Config and I added 'Valkyrian Skies' and it still crashes. Why?

**Comment by PriestOfFern** [comment]
> I have Rubidium for 1.19.2 and it doesn't crash

> I'm using 1.20.1

you don't see anything close to a discrepancy here?

**Comment by PriestOfFern** [comment]
in anycase, it's probably rubidium. There isn't a version of 1.20.1 rubidium, that works with VS2, as well as most addons.

Also this is a place for posting mod issues, not a place for dumping modpacks for other people to fix for you

**Comment by ewoudje** [comment]
No logs, discrepancy in explanation, and well its prob rubidum. Closing it in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556
