### ISSUE TITLE
I want to make a ship bigger than 32768 blocks

### ISSUE THREAD

**Issue by DEJKD** [ValkyrienSkies/Eureka#305]
### Mod Name

eureka 

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

i want to build a ship bigger than 32768 blocks it says i can change that number in the config but i don't know how 

### Issue reproduction

k

### Logs

no need

**Comment by Hex4dec** [comment]
Had this issue too, change the number in both client and server configs. It's confusing and bad UX. Not sure why this issue was closed.

**Comment by DosAEG** [comment]
Hey so, could you please elaborate more in "change the number in both client and server configs."? The only config file where  "maxShipBlocks" shows is in vs_eureka_server.json .

**Comment by Hex4dec** [comment]
Change the server config on client-side too. It shows up with Mod Menu i think
