### ISSUE TITLE
Valkyrien skies causes worldedit's //regen command to throw a fatal error.

### ISSUE THREAD

**Issue by joeyjumper94** [ValkyrienSkies/Eureka#322]
### Mod Name

worldedit

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

normally if a mod is incompatible with worldedit's //regen command, we see that it does nothing other than throwing a NONfatal error.
however here attempting to use worldedit's //regen command show an error, then the game freezes and crashes to desktop.

### Issue reproduction

make a curse forge profile, and install Valkyrien skies and worldedit
in game create a new world with commands allowed
once in a world, run these 3 commands in order
//pos1
//pos2
//regen
then crash to desktop.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Eureka/files/14811354/latest.log)
debug.log is not present.

**Comment by joeyjumper94** [comment]
[crash-2024-03-30_02.18.45-server.txt](https://github.com/ValkyrienSkies/Eureka/files/14811371/crash-2024-03-30_02.18.45-server.txt)

**Comment by millennIumAMbiguity** [comment]
This is not [Valkyrien Skies](https://github.com/ValkyrienSkies/Valkyrien-Skies-2)
