### ISSUE TITLE
Invisible animated or interactive objects

### ISSUE THREAD

**Issue by RapinaX** [ValkyrienSkies/Eureka#326]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​.1

### Mod Loader

Forge

### Issue description

I am using the Eureka Ships mod and I noticed this error caused by optimizer mods such as (Optifine, Rubidium, Embeddium and Embeddium++)

Any Block that has animation or is interactive becomes invisible if it is part of a ship created by (Eureka mod) including the mod's own helm

I have seen videos of other players who do not have this problem with animated blocks and I do not understand how it happens to me when using any of the mentioned ones (performance mods)
Is there a way to fix this and keep the animations?

The eureka mod works normally without any other mods, but when any of the others are installed this happens and playing without an optimizer causes a drop in FPS.

I am a Forge user

Screenshot:
![2024-04-04_13 18 40](https://github.com/ValkyrienSkies/Eureka/assets/166059814/9d71961d-c1c5-43db-8e2a-cef233fab82a)
![2024-04-04_13 21 35](https://github.com/ValkyrienSkies/Eureka/assets/166059814/960d7e24-bbd2-4954-9392-b6995c9d268f)

### Issue reproduction

Simply install the Eureka mod and its requirements (all updated) and combine it with Embeddium (0.3.11 / 0.3.12) or any optimizer (any version).

forge version: 47.2.0 for 1.20.1

### Logs

[debug.log](https://github.com/ValkyrienSkies/Eureka/files/14878096/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/14878097/latest.log)

**Comment by thetheaplant** [comment]
Please read ruby's comment on your previous post, use the newest embeddium (3.12 on forge) and disable entity culling on embeddium++, or remove it entirely. Additionally, this is a vs2, not a eureka issue.

**Comment by RapinaX** [comment]
> Please read ruby's comment on your previous post, use the newest embeddium (3.12 on forge) and disable entity culling on embeddium++, or remove it entirely. Additionally, this is a vs2, not a eureka issue.

I can't find my previous report...

It seems that it was deleted, I filtered everything by my user and it only detected this current one.
------
Yes, I already updated the embeddium and also tried deactivating (entity culling)

It already works :D
Thank you very much, in the previous version of Embeddium it did not work to deactivate (entity culling)
