### ISSUE TITLE
The Disassemble Button doesn't seem to work

### ISSUE THREAD

**Issue by Trent2Luigi** [ValkyrienSkies/Eureka#34]
Like the predecessors, *Italian Boats*, I hit the aline button to get it back in a grid position, but pushing the disassemble button doesn't make a click sound and does not return the blocks to a non physics abiding blocks. Figure I show mention this one.

**Comment by walksanatora** [comment]
did you enable it in config
(it is disabled by default iirc)

**Comment by ThePlasticPotato** [comment]
You see, it’s disabled for a reason- that being, the logic is about as functional as an appendix

**Comment by walksanatora** [comment]
it works *most of the time*
(as long as you deconstruct the ship the same direction it was facing when you built it)

**Comment by Rubydesic** [comment]
The fix for this issue has already been pushed and will be part of the next Curseforge release.
