### ISSUE TITLE
anchor applies upwards force while powered

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Eureka#346]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Eureka version

1.5.0-beta.1+f1aec78e18

### Mod Loader

Fabric

### Issue description

The anchor applies upwards momentum to your ship when it's powered.

https://github.com/ValkyrienSkies/Eureka/assets/101488091/b7b55bc2-83b0-429e-a5ca-5c112ddd0f47

### Issue reproduction

1. make a ship with an anchor and helm on it
2. power the anchor for a while
3. unpower the anchor
4. the ship should fly up

**Comment by millennIumAMbiguity** [comment]
im unable to recreate this

**Comment by AlexanderwithaA** [comment]
Are you using exactly what I am using? Latest fabric loader btw
