### ISSUE TITLE
anchor locks ship in air even when weight is greater than balloons can support

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Eureka#347]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Eureka version

1.5.0-beta.1+f1aec78e18

### Mod Loader

Fabric

### Issue description

If you make a ship then power the anchor, you can add more weight than the balloons/buoyancy can support but it will remain floating in place until unpowered. It'd be expected that the ship would slowly sink when there's too much weight as usual. Even with a powered anchor.

https://github.com/ValkyrienSkies/Eureka/assets/101488091/2ed85938-50ac-46ee-bd28-6e224a885d5e

### Issue reproduction

1. create a ship with a helm and anchor
2. power the anchor
3. add more weight ie: gold block
4. ship will remain in place even though it wouldn't be able to support it's weight

**Comment by millennIumAMbiguity** [comment]
This is intentional. (not my choice tho)
