### ISSUE TITLE
holding shift + rightclick to look at helm causes data to become empty

### ISSUE THREAD

**Issue by AlexanderwithaA** [ValkyrienSkies/Eureka#349]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Eureka version

1.5.0-beta.1+f1aec78e18

### Mod Loader

Fabric

### Issue description

When you hold shift+rclick and look at the helm the ui opens and all the data flashes before disappearing

https://github.com/ValkyrienSkies/Eureka/assets/101488091/0ed9b52b-600f-41f5-a37f-e0dfdf86749a

### Issue reproduction

1. hold rclick+shift
2. pan across the helm
3. ui will open, data will flash, ui will become empty

**Comment by millennIumAMbiguity** [comment]
issue cased by the ui is using a ray cast from view to find the helm.

**Comment by millennIumAMbiguity** [comment]
I think I know a fix
