### ISSUE TITLE
Ships not interactable on a server, but are okay on singleplayer worlds.

### ISSUE THREAD

**Issue by drewdoesdumbstuff** [ValkyrienSkies/Eureka#363]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Eureka version

alpha6

### Mod Loader

Forge

### Issue description

Playing forge 1.16.5 with eureka installed. On a server, whenever anyone tries assembling a ship, the ship only exists as blocks you can't interact with, only being able to collide with them. This does not happen in a singleplayer world with the same modpack. Is there any way to fix this? I know 1.16 isnt supported but I have no other choice.

### Issue reproduction

Go into a server and try assembling a ship.

### Logs

[debug.log](https://github.com/ValkyrienSkies/Eureka/files/15288231/debug.log)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/15288232/latest.log)

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
