### ISSUE TITLE
[suggestion] add a limit for blocks on a ship

### ISSUE THREAD

**Issue by FatalError20** [ValkyrienSkies/Eureka#394]
my friend and me had a world where we built a ship but its (somehow) connected with the world and made it completly bricked
if you alread have a limit , add a option to change the limit

**Comment by Danielville7777** [comment]
there is a limit and it can be changed in config in the vs_eureka_server.json file near the bottom

**Comment by FatalError20** [comment]
> there is a limit and it can be changed in config in the vs_eureka_server.json file near the bottom

ah ok thanks
