### ISSUE TITLE
<title>1.20.1 beta-6 crash

### ISSUE THREAD

**Issue by REFIRSER2** [ValkyrienSkies/Eureka#400]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Eureka version

1.5.1-beta.3

### VS2 version

2.3.0-beta.6

### Mod Loader

Forge

### Issue description
if load valkyrian skies 2.3.0 beta.6 then cause eureka load error.

### Issue reproduction
if load valkyrian skies 2.3.0 beta.6 then cause eureka load error.

### Logs

[latest.log](https://github.com/user-attachments/files/16939032/latest.log)

**Comment by thetheaplant** [comment]
![Screenshot (59)](https://github.com/user-attachments/assets/df737e61-3785-411e-a1cc-9d79af469e29)
What do you think this checkbox means?

**Comment by REFIRSER2** [comment]
Ah! My mistake. sorry. I close issue and re open issue of compatibility.
