### ISSUE TITLE
<title>1.20.1 terrafirma compat crash

### ISSUE THREAD

**Issue by REFIRSER2** [ValkyrienSkies/Eureka#402]
### Mod Name

terrafirma

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

When load mod with terrafirma then cause crash.

### Issue reproduction

When load mod with terrafirma then cause crash.

### Logs

[latest.log](https://github.com/user-attachments/files/16939032/latest.log)

**Comment by PriestOfFern** [comment]
Not a eureka issue.

fixed in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/833
