### ISSUE TITLE
Sides of Blocks dissapearing

### ISSUE THREAD

**Issue by Serial-Designation-V** [ValkyrienSkies/Eureka#424]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Eureka version

v1.3.0-beta.4

### VS2 version

v2.3.0-beta.5

### Mod Loader

Forge

### Issue description

While building a ship or Airship, Sides of Blocks start to dissapear, like on this Photo of a Unfinished Airship, the Hull started to Dissapear
![obraz_2024-11-19_180808140](https://github.com/user-attachments/assets/4ac9085f-ff61-47c5-adae-1717cd312980)

### Issue reproduction

Just try to Build a Ship/Airship. It will then occur

**Comment by Serial-Designation-V** [comment]
i also tested it on other versions of this Mod, v1.5.1-beta.3 and v1.5.0-beta.3, same issue occurs

**Comment by thetheaplant** [comment]
So you did everything except check the wiki, google it, or check previous issues.

**Comment by Serial-Designation-V** [comment]
Alright, found the solution on Reddit, thanks

**Comment by thetheaplant** [comment]
For other people who will find this post looking for the solution, https://wiki.valkyrienskies.org/wiki/Common_Issues#Ship_is_only_partly_visible,_block_faces_are_missing
