### ISSUE TITLE
Bug Makes It Where Sometimes a VS Contraption Does Not Halt Movement After The Player Leaving a Helm.

### ISSUE THREAD

**Issue by MystorioC** [ValkyrienSkies/Eureka#53]
When a Player Disengages With The Helm While Controlling a Moving VS Contraption, Most of The Time The VS Contraption Does Not Stop Moving, And It Can Not Be Stopped Unless It Hits an Obstacle. _**This was Discovered While Playing With Friends on a Disposable Server.**_

**Comment by Rubydesic** [comment]
Do you have cruise control enabled? (C keybind)
