### ISSUE TITLE
VS Eureka Mod (vs_eureka) has failed to load correctly

### ISSUE THREAD

**Issue by TheStarlessBandit** [ValkyrienSkies/Eureka#57]
A player tried to run a modpack, and got this error.
The modpack has all the dependencies and runs fine for everyone else.
Minecraft version 1.16.5

[message.txt](https://github.com/ValkyrienSkies/Eureka/files/10198240/message.txt)

**Comment by Mamjaxsed** [comment]
А как исправить ошибку то?
