### ISSUE TITLE
[Forge 1.18.2] Game Crash instantly at start.

### ISSUE THREAD

**Issue by zalfrost** [ValkyrienSkies/Eureka#60]
**Forge Version:** 
-Forge 1.18.2 40.1.86

**Optifine Version:** 
-Optifine 1.18.2 HD U H9 Preview 2

**Mod Version:**
-Eureka: 1.18.2 version 1.1.0 beta 2
-Valkyrie Skies: 1.18.2 version 2.1.0 beta 1

**Issues recreate:** 
-Run Minecraft with Optifine.
-Crash immediately after.

**Additional Info:**
-I think it has something to do with Optifine though I haven't tried it without Optifine yet. Will updated as soon as I try without Optifine.

**Log/Crash Log File:**
-Log file: https://pastebin.com/2iZeY2NV
-Crashlog: None are created as it crashes immediately.

**Comment by zalfrost** [comment]
**UPDATE**

The issue doesn't seem to be Optifine. I don't know what caused it to crash right away.

**Log/Crashlog File:**
-Log file: https://pastebin.com/eD3p8qub (Update without Optifine)

**Comment by ThePlasticPotato** [comment]
You have a lot more mods than _just_ optifine- it'd be worth making sure none of them are listed as incompatible on the wiki.

**Comment by zalfrost** [comment]
I will try to check that out. 👍

**Comment by zalfrost** [comment]
Seems like they listed one of the performance optimizes mods as incompatible in the 1.16 list. I guess the same problem goes for some of the performance mods that I got. Too bad for me then.
