### ISSUE TITLE
ship engine doesnt return bucket

### ISSUE THREAD

**Issue by awesomebossdj7** [ValkyrienSkies/Eureka#64]
when putting a lava bucket into the ship engine, it does not return a bucket.

side note:
please make it so that you can connect a pipe to it, and pump in lava

**Comment by millennIumAMbiguity** [comment]
I would suggest that instead of adding the ability to connect pipes and pump in lava, there should be a separate engine for fluids. A liquid fuel engine you could say. I would like to see it take in liquid fuel and water to produce trust, like a steam engine. In return, it can grant higher power and longer burn time than putting a bucket in a solid-fuel engine.

**Comment by TechTastic** [comment]
> I would suggest that instead of adding the ability to connect pipes and pump in lava, there should be a separate engine for fluids. A liquid fuel engine you could say. I would like to see it take in liquid fuel and water to produce trust, like a steam engine. In return, it can grant higher power and longer burn time than putting a bucket in a solid-fuel engine.

unfortunately, that requires a bit of custom Fluid Handling as Architectury does not have its own past making new liquids

**Comment by millennIumAMbiguity** [comment]
> > I would suggest that instead of adding the ability to connect pipes and pump in lava, there should be a separate engine for fluids. A liquid fuel engine you could say. I would like to see it take in liquid fuel and water to produce trust, like a steam engine. In return, it can grant higher power and longer burn time than putting a bucket in a solid-fuel engine.
> 
> unfortunately, that requires a bit of custom Fluid Handling as Architectury does not have its own past making new liquids

I would imagine, just wanted to make sure my thought about the side note is logged before this issue is closed and I forget about it. I believe that the side note should be its own separate issue. It might be more fitting for such a feature to be a separate addon.
