### ISSUE TITLE
Forge 1.18.2 Server does not start with Eureka/Valkyrien Sky

### ISSUE THREAD

**Issue by HoodBlah** [ValkyrienSkies/Eureka#65]
When trying to start a forge 1.18.2 server with both create and eureka airships, an error occurs saying that create cannot be loaded properly. This problem does not occur on clients.
[debug.log](https://github.com/ValkyrienSkies/Eureka/files/10243074/debug.log)

**Comment by strontix** [comment]
I am having the same problem
[debug.log](https://github.com/ValkyrienSkies/Eureka/files/10251188/debug.log)

**Comment by strontix** [comment]
Nevermind! [v2.1.0-beta6](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies/files/4183507) fixed this issue!
Tested with Forge 1.18.2-40.1.69
