### ISSUE TITLE
hopper minecart cannot insert items into engine

### ISSUE THREAD

**Issue by awesomebossdj7** [ValkyrienSkies/Eureka#72]
make hopper minecarts work with the ship engine

**Comment by millennIumAMbiguity** [comment]
While testing with Eureka 1.5.0 on Minecraft 1.20.1 I find the following
1. you can extract using a hopper or hopper minecart
2. you cannot transfer between ship and non-ship using a hopper minecart (not a bug)
3. hopper minecart cannot insert items (this is a bug)

**Comment by LordPhyre** [comment]
> While testing with Eureka 1.5.0 on Minecraft 1.20.1 I find the following
> 
> 1. you can extract using a hopper or hopper minecart
> 2. you cannot transfer between ship and non-ship using a hopper minecart (not a bug)
> 3. hopper minecart cannot insert items (this is a bug)

Number 3 does not occur on 1.18.2.

**Comment by TedKaczynskisCousin** [comment]
> > While testing with Eureka 1.5.0 on Minecraft 1.20.1 I find the following
> > 
> > 1. you can extract using a hopper or hopper minecart
> > 2. you cannot transfer between ship and non-ship using a hopper minecart (not a bug)
> > 3. hopper minecart cannot insert items (this is a bug)
> 
> Number 3 does not occur on 1.18.2.

Just realized that hopper minecarts cannot insert items. They aren't supposed to do that. I was thinking of chest minecarts. Number 3 is not a eureka issue.

**Comment by TedKaczynskisCousin** [comment]
Oh yeah, and that means this issue isn't a bug either. Someone close it

**Comment by millennIumAMbiguity** [comment]
oh you are right
