### ISSUE TITLE
Bugs when trying to make a TNT cannon

### ISSUE THREAD

**Issue by FernandoCalaza** [ValkyrienSkies/Eureka#75]
I tried to make 1x7 TNT cannons and noticed 3 bugs:
- Activated TNT are stuck in the blocks of the cannon walls, prevented from moving
- Activated TNT are not carried by water flow
- Activated TNT follows world orientation instead of ship orientation. Sometimes they go through blocks exploding everything, by getting out of the water.

Mod version: Eureka! Airships! [Fabric 1.18.2] v1.1.0-beta2

Used with mods:
- valkyrienskies-118-fabric-2.1.0-beta1+0c28d02ed5
- Mods from: Fabulously Optimized 3.14.1 for 1.18.2 (CurseForge)

**Comment by ThePlasticPotato** [comment]
Tnt cannons are not supported and won’t be in their current state- that’s something that’ll have to be done via either a custom type of tnt or some jank with making it a shipyard entity.

**Comment by Rubydesic** [comment]
known and not really a bug, vanilla tnt can't rotate. much debate about how to solve this problem
