### ISSUE TITLE
Not work with immersive portals

### ISSUE THREAD

**Issue by UrbanSide** [ValkyrienSkies/Eureka#77]
In general, as in the topic title, the mod does not work with these portals ... The ship is created, then it starts pulling out structures from other worlds (if Dimension Stack is enabled)

**Comment by TechTastic** [comment]
If you can, check this with VS2 alone to see if its explicitly a Eureka issue as I believe it is just incompatibility with VS2 as a whole due to how Immersive Portals works

**Comment by ThePlasticPotato** [comment]
a good key is: if its a mod that overhauls rendering, and its not explicitly stated as compatible, tread carefully

**Comment by UrbanSide** [comment]
thanks for the answers, it's a pity not to combine them, I really wanted to ...

**Comment by TechTastic** [comment]
> thanks for the answers, it's a pity not to combine them, I really wanted to ...

no problem, theyll prob be compat made sometime as 2 future addons plan to rely on Immersive Portals for dimension crossing, but for now, they are incompatible
