### ISSUE TITLE
after activating the assemble the blocks will disappear

### ISSUE THREAD

**Issue by Ghostbuu** [ValkyrienSkies/Eureka#84]
Hello, I have a problem when activating the Assemble in the oak ship helm, it seems that I use the wonder woman plane. If someone helps me oh better update more for 1.18.2, I'll be grateful thanks.

**Comment by copperwarrior** [comment]
Please provide a list of any other mods you are using.

**Comment by Rubydesic** [comment]
remove optifine if you have it. re-open with latest.log and a list of mods if you still have a problem
