### ISSUE TITLE
When assembling, assemblies turn invisible and cease function.

### ISSUE THREAD

**Issue by MrSirSquishy** [ValkyrienSkies/Eureka#87]
whenever I assemble a structure it goes invisible, and works weirdly. after assembly, it can't be accessed in any way, though it still detects a structure in its place. The only way to interact with it is by walking into it, and it will freeze the player in place with the only way to get out being teleportation.

1.18.2 Forge

**Comment by Rubydesic** [comment]
This sounds like a mod incompatibility, please identify the mod that is causing this issue, launch the game with only eureka and that mod installed, and send your .minecraft/logs/latest.log file here.

**Comment by FrancoInca** [comment]
I had the same problem, disabling Optifine fix it.

**Comment by Rubydesic** [comment]
Optifine is not supported in 1.18+. Disable Optifine and re-open this issue if you still have problems. Rubidium/Oculus is recommended for shaders on Forge.
