### ISSUE TITLE
crashing when placing tile entities on assembled structure.

### ISSUE THREAD

**Issue by MrSirSquishy** [ValkyrienSkies/Eureka#88]
**Describe the bug and how to make it happen:**
When using a ship, I attempted to place a chest on the ship, which ended up crashing the game with Exit code 1

**Does the bug happen without other mods?**
No(only happens with create)

**If applicable, which other mod causes the bug?**
Create/Flywheel

**latest.log**
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/10347384/latest.log)

**Comment by Rubydesic** [comment]
Create 0.5g not supported, use 0.5e
