### ISSUE TITLE
Ship getting randomly flinged millions blocks out

### ISSUE THREAD

**Issue by LopyLuna** [ValkyrienSkies/Eureka#94]
**Describe the bug and how to make it happen:**
Ship getting randomly flinged millions blocks out as the title says I cant get more info about this, tho I found out when trying to turn the boat I think im not fully sure

![image](https://user-images.githubusercontent.com/100169742/212388370-b23f3a47-c8ae-4a79-ad1a-d01f4447316b.png)

**Does the bug happen without other mods?**
Yes

**Comment by Bottinator22** [comment]
you weren't flung millions of blocks out, you were teleported millions of blocks out
you have been warped to the shipyard, and that structure you see there is probably your ship in the shipyard, immovable and completely world-bound

what MC version did you use?

**Comment by LopyLuna** [comment]
1.18.2 forge most recent version of the mod

**Comment by copperwarrior** [comment]
Random occurrences like this are difficult to debug. Please try and find out what is causing you to be transported to the shipyard.

**Comment by Rubydesic** [comment]
probably fixed in beta10
